version: '3'
services:
  base-project-pg:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=confectionery-store
    ports:
      - '5433:5432'

#  cd  docker
#  docker-compose -f postgres.yaml up -d